version: '3'

volumes:
  redis_vol:
  mysql_vol:

services:
  guestbook:
    build: .
    volumes:
      - ./:/code
      context: .
      dockerfile: ./Dockerfile
      args:
        GIT_REPO: git@github.com:jbthemc/test_guestbook.git
        GIT_BRANCH: master
        PRIVATE_KEY: $(cat ~/.ssh/id_rsa)
    ports:
      - "8080:5000"
    environment:
      REDIS_HOST: redis
      MYSQL_DATABASE_HOST: mysql
      MYSQL_DATABASE_USER: root
      MYSQL_DATABASE_PASSWORD: password1
      MYSQL_DATABASE_DB: website
    restart: always
  redis:
    image: "redis:alpine"
    volumes:
      - redis_vol:/data
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: website
      MYSQL_ROOT_PASSWORD: password1
    volumes:
      - mysql_vol:/var/lib/mysql

