version: '3'

volumes:
  redis_vol:
  mysql_vol:
  
services:
  guestbook:
    build:
    volumes:
      - ./:/code
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:5000"
    environment:
      REDIS_HOST: redis
      MYSQL_DATABASE_HOST: root
      MYSQL_DATABASE_USER: password1
      MYSQL_DATABASE_PASSWORD: website
      MYSQL_DATABASE_DB: mysql
    restart: always
  redis:
    image: "redis:alpine"
    volumes:
      - redis_vol:/data
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: website
      MYSQL_ROOT_PASSWORD: password1
    volumes:
      - mysql_vol:/var/lib/mysql

