version: '3'

services:
  guestbook:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        GIT_REPO: ${GIT_REPO}
        GIT_BRANCH: ${GIT_BRANCH}
        PRIVATE_KEY: ${PRIVATE_KEY}
    ports:
      - "8080:5000"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      MYSQL_DATABASE_HOST: ${DB_HOST}
      MYSQL_DATABASE_USER: ${DB_USER}
      MYSQL_DATABASE_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE_DB: ${DB_NAME}
    restart: always
